### ISSUE TITLE
How do i insert the mod in Lethal company?

### ISSUE THREAD

**Issue by Pizzakopf** [lawrencea13/GameMaster2.0#1]
The title says it all, i need help...

**Comment by RedStoneCraftGG** [comment]
Find the Lethal Company game folder first (depending on where you put the game folder), then place the mod inside ```/BepInEx/plugins/```. If you don't have BepInEx yet, I recommend downloading it first.

**Comment by lawrencea13** [comment]
Download the latest release [here](https://github.com/lawrencea13/GameMaster2.0/releases/tag/EarlyAccess) and install it like any other mod. If you need help setting up mods, I have a guide [here.](https://www.youtube.com/watch?v=eXA60ZWMI4M)
